# ./docker-compose.yml

version: "3.1"

networks:
  orders-network:
    external: true
volumes:
  postgres:
    driver: local
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - orders-network
    
  postgres:
    image: postgres:13.3
    container_name: db_balances
    restart: always
    environment: 
      POSTGRES_USER: "postgre"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5430:5432" 
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - orders-network
  balance-service:
    image: balanceservicebalances:latest
    container_name: balance-service
    restart: always
    networks:
      - orders-network
    depends_on:
      - rabbitmq
  redis:
    image: redis:latest
    container_name: db_orders
    restart: always
    ports:
      - "6379:6379"
    networks:
      - orders-network
  order-processing:
    image: orderproccesing:latest
    container_name: orderprocessing
    restart: always
    networks:
      - orders-network
    depends_on:
      - redis
  quotes-manager:
    image: quotemanager:latest
    container_name: quotemanager
    restart: always
    networks:
      - orders-network
    depends_on:
      - redis
        